name: "FHIR IG Action"
description: "Worklow pour les IG de l'ANS"
inputs:
  repo:
    description: "Chemin d'accés au repertoire de l'IG"
    required: true
runs:
  using: "composite"
  steps:

      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install saxon
        shell: bash   
        run : pip install saxonche

      - name: Run script plantuml      
        shell: bash   
        continue-on-error: true
        run : |
              cd  ${{ inputs.repo}}
              python ${{ github.action_path }}/tools/validate.py './${{ inputs.repo_ig}}/output/package.db' './plantuml/graph.puml'
              echo "### Rapport de validation (validator_cli)  :rocket:" >> $GITHUB_STEP_SUMMARY
              cat ./validator_cli/rapport.html >> $GITHUB_STEP_SUMMARY

       




branding:
  icon: 'check'
  color: 'blue'

          
